image: 'docker-registry.dexguru.biz/dex.guru/warehouse-api/warehouse-api'
imageTag: ''
registrySecretName: registry-harbor

app:
  strategyType: 'RollingUpdate'
  baseEnv:
    APM_SERVER_URL: "http://apm-server-external-apm-server.logging.svc.cluster.local:8200"
    APM_ENABLED: 'False'
    APM_RECORDING: 'False'
    APM_CAPTURE_HEADERS: 'False'
    LOGGING_LEVEL: 'INFO'
    LOG_HANDLERS: '["console"]'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    ENVIRONMENT: "prod"
    # External Services Settings (API Keys for example)
    SENTRY_DSN: ""
    AMPLITUDE_API_KEY: ""
    POSTHOG_API_KEY: ""
    # Performance Monitoring System Settings
    PROMETHEUS_PORT: 9090
    GRAFANA_PORT: 3000
    GRAFANA_ADMIN_USER: "admin"
    GRAFANA_ADMIN_PASSWORD: "admin"
    ETHERSCAN_API_KEY: "SOME_API_KEY"
