image: ''
imageTag: ''
registrySecretName: registry-harbor

app:
  replicas:
    default: 1
  port: 8000
  serviceType: NodePort
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 1
  requestsMemory: 1G
  strategyType: 'RollingUpdate'
#  readnessProbe:
#    path: '/health_check'
#    port: '8000'
#  livenessProbe:
#    path: '/health_check'
#    port: '8000'
  baseEnv:
    APM_SERVER_URL: "http://apm-server-apm-server.logging.svc.cluster.local:8200"
    APM_ENABLED: 'True'
    APM_RECORDING: 'True'
    APM_CAPTURE_HEADERS: 'False'
    LOGGING_LEVEL: 'INFO'
    LOG_HANDLERS: '["console"]'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    ENVIRONMENT: "stage"
    SENTRY_DSN: ""
    AMPLITUDE_API_KEY: ""
    POSTHOG_API_KEY: ""
    # Performance Monitoring System Settings
    PROMETHEUS_PORT: 9090
    GRAFANA_PORT: 3000
    GRAFANA_ADMIN_USER: "admin"
    GRAFANA_ADMIN_PASSWORD: "admin"
  env:
    SERVICE_NAME: "artfusion-bot"
    WORKERS: '5'
    # Telegram Bot Settings

