image: "docker-registry.dexguru.biz/dex.guru/guru-network-fe/guru-network-fe/guruv2-stage"
frontend:
  replicas:
    default: 1
  port: 3000
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 1
  requestsMemory: 1G
  env:
    SERVICE_NAME: "guru-network-app-stage"
    AUTH_SECRET: "W4EJ6xXm1qEGkCOuMimx+Gy20Pdrz+Hce4EsBqXI7tQ="
    FLOW_API_URL: "http://guru-network-be-flow-api.guru-network-be.svc.cluster.local:8000"
    SYS_KEY: "6nbHOIkd7hly"
    FLOW_API_SYS_KEY: "jccHUEFKeR4b5"
    AUTH_TRUST_HOST: "true"
    WAREHOUSE_API_HOST: "https://warehouse.dex.guru"
    WAREHOUSE_API_KEY: "PKhNXBIYGG8sLBSBW9e4h5h5pb1lfUXMhokiMQu1"
    LANGCHAIN_API_URL: "https://langchain-prod.dexguru.biz"
    LANGCHAIN_API_KEY: "19359a61ae2446b51b549167b014da2fcf265768"
  ingressHosts:
    - name: "app-stage-guru-network"
      host: "app-stage.gurunetwork.ai"
