app:
  replicas:
    default: 1
  port: 8000
  serviceType: NodePort
  limitsCpu: 0.5
  limitsMemory: 0.5G
  requestsCpu: 0.5
  requestsMemory: 0.5G
  strategyType: 'RollingUpdate'
  command: '[ "python", "./bot_server/__main__.py" ]'
  env:
    SERVICE_NAME: "bot-app"
    # Telegram Bot Settings
    BOT_TOKEN: "BOT_TOKEN"
    SUPPORT_URL: "docs.gurunetwork.ai"
    TELEGRAM_APP_LINK: "https://t.me/bot_name/bot_name"
    TELEGRAM_BOT_NAME: "generation_bets_bot"
    RATE_LIMIT: 0.5
    DEBUG: True
    # Webhook Server Settings (Optional)
    USE_WEBHOOK: False
    WEBHOOK_HOST: "0.0.0.0"  # use "localhost" if not using Docker
    WEBHOOK_PORT: 8080
    WEBHOOK_BASE_URL: "https://example.com"
    WEBHOOK_PATH: "/webhook"
    WEBHOOK_SECRET: "secret"
    # Admin Panel Settings
    ADMIN_HOST: "0.0.0.0"    # use "localhost" if not using Docker
    ADMIN_PORT: 8000
    DEFAULT_ADMIN_EMAIL: "email@example.com"
    DEFAULT_ADMIN_PASSWORD: "secret"
    SECURITY_PASSWORD_HASH: "hash"
    SECURITY_PASSWORD_SALT: "salt"
    SYS_KEY: "secret"
    FLOW_API: "http://nft-mania-flow-api.nft-mania.svc.cluster.local:8000"
    FLOW_SYS_KEY: "secret"
    AUTHJWT_SECRET_KEY: "secret"
    # Camunda Engine
    ENGINE_ADMIN_PREFIX: "https://nft-mania-engine-api.gurunetwork.ai"
    ENGINE_URL: "http://nft-mania-engine-api.nft-mania.svc.cluster.local:8080/engine-rest"
    ENGINE_USERNAME: "demo"
    ENGINE_PASSWORD: "demo"
    ENGINE_USERS_GROUP_ID: "camunda-admin"
    # Redis (for FSM and Cache) Settings
    REDIS_URL: redis://redis-master:6379/8
    REDIS_HOST: "redis-master"      # use "localhost" if not using Docker
    REDIS_PORT: 6379
    REDIS_DATABASE: 10
    AMPLITUDE_API_KEY: ""
    PYTHONPATH: .

