---
image: ''
imageTag: ''
registrySecretName: registry-harbor

app:
  replicas:
    default: 1
  port: 8080
  serviceType: NodePort
  limitsCpu: 2
  limitsMemory: 2G
  requestsCpu: 1
  requestsMemory: 1G
  strategyType: 'RollingUpdate'
  readnessProbe:
    path: '/health_check'
    port: '8080'
  livenessProbe:
    path: '/health_check'
    port: '8080'
  baseEnv:
    ENVIRONMENT: "stage"
  env:
    LOGGING_LEVEL: 'INFO'
