image: "docker-registry.dexguru.biz/dex.guru/dep-guru-framework/dep-guru-framework/guruv2-stage"
frontend:
  replicas:
    default: 1
  port: 3000
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 1
  requestsMemory: 1G
  env:
    SERVICE_NAME: "guru-network-app-prod"
    NEXT_PUBLIC_PROJECT_ID: 44fddbdad1f7789c6ea7289c899d4da5
    # NEXT_PUBLIC_GA_TRACKING_ID: G-617E968S0R
    # NEXT_PUBLIC_YANDEX_METRICA_ID: 98186048
    AUTH_SECRET: "W4EJ6xXm1qEGkCOuMimx+Gy20Pdrz+Hce4EsBqXI7tQ="
    FLOW_API_URL: "http://guru-network-be-flow-api.guru-network-be.svc.cluster.local:8000"
    SYS_KEY: "jccHUEFKeR4b5"
    FLOW_API_SYS_KEY: "jccHUEFKeR4b5"
    AUTH_TRUST_HOST: "true"
    WAREHOUSE_API_HOST: "https://warehouse.dex.guru"
    WAREHOUSE_API_KEY: "PKhNXBIYGG8sLBSBW9e4h5h5pb1lfUXMhokiMQu1"
    LANGCHAIN_API_URL: "https://langchain-prod.dexguru.biz"
    LANGCHAIN_API_KEY: "19359a61ae2446b51b549167b014da2fcf265768"
  ingressHosts:
    - name: "burning-meme-prod"
      host: "app.gurunetwork.ai"
