frontend:
  replicas:
    default: 1
  serviceType: NodePort
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 1
  requestsMemory: 1G
  strategyType: 'RollingUpdate'
  workingDir: '/app/src/'
  baseEnv:
    REDIS_URL: "redis://10.0.100.43:6379"
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://10.0.100.154:4318/v1/traces
    OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
  letsencrypt:
    issuer: "letsencrypt-prod"
