---
image: 'PUT_IMAGE_IN_ENV_VALUES_FILE'
imageTag: ''
registrySecretName: registry-harbor

frontend:
  replicas:
    default: 1
  port: 3000
  serviceType: NodePort
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 1
  requestsMemory: 1G
  strategyType: 'RollingUpdate'
  workingDir: '/app/src/'
  env:
    SERVICE_NAME: "meme-app"
    NEXT_PUBLIC_API_HOST: https://api.dex.guru
    NEXT_PUBLIC_WS_HOST: wss://ws.dex.guru
  baseEnv:
    LOGGING_LEVEL: 'INFO'
    LOG_HANDLERS: '["console", "logstash"]'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    NEXT_PUBLIC_APM_SERVER_URL: "http://apm-server-apm-server.logging.svc.cluster.local:8200"
    NEXT_PUBLIC_APM_RUM_URL: "https://apm-stage-lax.dexguru.biz"
  letsencrypt:
    issuer: "letsencrypt-prod"
