app:
  replicas:
    default: 1
  port: 8080
  limitsCpu: 2
  limitsMemory: 4G
  requestsCpu: 2
  requestsMemory: 4G
  readnessProbe:
    path: '/actuator/health'
    port: '8080'
  livenessProbe:
    path: '/actuator/health'
    port: '8080'
  env:
    SERVICE_NAME: "engine-api-nft-mania"
    BBPA_ENGINE_DB_DRIVER_CLASS: org.postgresql.Driver
    BBPA_ENGINE_DB_DRIVER: postgresql
    BBPA_ENGIN_DB_USER: postgres
    BBPA_ENGIN_DB_PASS: SuperSecretPassword
    BBPA_ENGINE_DB_URL: jdbc:postgresql://postgres-postgresql:5432/engine   
    API_URL: "http://nft-mania-flow-api.nft-mania.svc.cluster.local:8000"
    API_KEY: "secret"
    BOT_NAME: "bot_name"
    RABBITMQ_ENABLED: false
    RABBITMQ_HOST: rabbimq
    RABBITMQ_PORT: 5672
    RABBITMQ_USER: admin
    RABBITMQ_PASSWORD: admin
    RABBITMQ_VIRTUAL_HOST: /
    RABBITMQ_EXCHANGE: nft_mania_app_engine
    RABBITMQ_QUEUE: nft_mania_app_engine
    RABBITMQ_ROUTINGKEY: nft_mania_app_engine
    INSCRIPTIONS_HISTORY_ENABLED: false
    INSCRIPTIONS_RPC_URL: https://rpc.gurunetwork.ai/archive/261
    INSCRIPTIONS_CHAIN: 261
    INSCRIPTIONS_PRIVATEKEY: 0000000000000000000000000000
    INSCRIPTIONS_MAX_THREADS: 8
    INSCRIPTIONS_QUEUE_CAPACITY: 10000
    INSCRIPTIONS_BATCH_SIZE: 32
    JOB_EXECUTION_ENABLE: true
    JOB_EXECUTION_MAX_POOL_SIZE: 30
    JOB_EXECUTION_MAX_JOBS_PER_ACQ: 10
    JOB_EXECUTION_CORE_POOL_SIZE: 10
    CHAIN_ID: 261
  ingressHosts:
    - name: "engine-app-nft-mania"
      host: "nft-mania-engine.apps.dexguru.net"

