---
image: ''
imageTag: ''
registrySecretName: registry-harbor

app:
  replicas:
    default: 1
  port: 3000
  serviceType: NodePort
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 1
  requestsMemory: 1G
  strategyType: 'RollingUpdate'
  workingDir: '/app/src/'
  baseEnv:
    LOGGING_LEVEL: 'INFO'
    LOG_HANDLERS: '["console"]'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"

