app:
  replicas:
    default: 1
  port: 8000
  serviceType: NodePort
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 0.1
  requestsMemory: 0.2G
  strategyType: 'RollingUpdate'
  command: '[ "sh", "-c", "/usr/src/app/launch.sh" ]'
  readnessProbe:
    path: '/api/health_check'
    port: '8000'
  livenessProbe:
    path: '/api/health_check'
    port: '8000'
  env:
    # Telegram Bot Settings
    BOT_TOKEN: "BOT_TOKEN"
    SUPPORT_URL: "api.gurunetwork.ai"
    RATE_LIMIT: 0.5
    DEBUG: True
    # Webhook Server Settings (Optional)
    USE_WEBHOOK: False
    WEBHOOK_HOST: "0.0.0.0"  # use "localhost" if not using Docker
    WEBHOOK_PORT: 8080
    WEBHOOK_BASE_URL: "https://example.com"
    WEBHOOK_PATH: "/webhook"
    WEBHOOK_SECRET: "secret"
    SERVICE_NAME: "nft-mania-api"
    # Admin Panel Settings
    ADMIN_HOST: "0.0.0.0"    # use "localhost" if not using Docker
    ADMIN_PORT: 8000
    DEFAULT_ADMIN_EMAIL: "email@example.com"
    DEFAULT_ADMIN_PASSWORD: "secret"
    SECURITY_PASSWORD_HASH: "secret"
    SECURITY_PASSWORD_SALT: "secret"
    SYS_KEY: "secret"
    AUTHJWT_SECRET_KEY: "secret"
    # Database Settings
    DB_HOST: "postgres-postgresql"     # use "localhost" if not using Docker
    DB_PORT: 5432
    DB_USER: "postgres"
    DB_PASS: "SuperSecretPassword"
    DB_NAME: "flow_api"

    # Camunda Engine
    ENGINE_URL:  "http://nft-mania-engine-api.nft-mania.svc.cluster.local:8080/engine-rest"
    ENGINE_USERNAME: "demo"
    ENGINE_PASSWORD: "demo"
    # Redis (for FSM and Cache) Settings
    REDIS_URL: "redis://redis-master:6379/8"
    REDIS_HOST: "redis-master"     # use "localhost" if not using Docker
    REDIS_PORT: 6379
    REDIS_DATABASE: 11
    AMPLITUDE_API_KEY: ""
    # APM
    APM_SERVER_URL: "http://apm-server-external-apm-server.logging.svc.cluster.local:8200"
    APM_ENABLED: 'False'
    APM_RECORDING: 'False'
    APM_CAPTURE_HEADERS: 'False'
    ENVIRONMENT: "prod"
    PYTHONPATH: "/usr/src/app"
    GENERATE_SCHEMA: "True"
  ingressHosts:
    - name: "flow-nft-mania"
      host: "nft-mania-flow.apps.dexguru.net"

