app:
  replicas:
    default: 3
  port: 8000
  serviceType: NodePort
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 0.1
  requestsMemory: 0.2G
  strategyType: 'RollingUpdate'
  command: '[ "python", "./fa_admin/__main__.py" ]'
  readnessProbe:
    path: '/api/health_check'
    port: '8000'
  livenessProbe:
    path: '/api/health_check'
    port: '8000'
  env:
    SERVICE_NAME: "landing-prod"
  ingressHosts:
    - name: "nft-mania"
      host: "gurunetwork.ai"

