---
image: ''
imageTag: ''
registrySecretName: registry-harbor

app:
  replicas:
    default: 1
  limitsCpu: 1
  limitsMemory: 9000Mi
  requestsCpu: 0.1
  requestsMemory: 1000Mi
  command: '[ "python", "./web3_workers/check_transaction_status.py" ]'
  strategyType: 'RollingUpdate'
  ##
  env:
    SERVICE_NAME: 'ia-web3-auto-transaction-status'
  baseEnv:
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
