app:
  replicas:
    default: 1
  port: 3000
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 1
  requestsMemory: 1G
  env:
    SERVICE_NAME: "guru-network-app-prod"
    NEXT_PUBLIC_PROJECT_ID: wallet_connect_id
    # NEXT_PUBLIC_GA_TRACKING_ID: G-617E968S0R
    # NEXT_PUBLIC_YANDEX_METRICA_ID: 98186048
    FLOW_API_URL: "http://nft-mania-flow-api.nft-mania.svc.cluster.local:8000"
    SYS_KEY: "secret"
    FLOW_API_SYS_KEY: "secret"
    AUTH_TRUST_HOST: "true"
  ingressHosts:
    - name: "nft-mania-app-prod"
      host: "nft-mania-app.apps.dexguru.net"
